# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets

import database
from main import main_form


class login_form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 640)

        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        Form.setStyleSheet("QWidget{\n"
                           "image: url(:/background/Resources/1920x1080-px-Moon-satellite-simple-space-1473897.jpg);\n"
                           "\n"
                           "}")
        self.input_fileds_frame = QtWidgets.QFrame(Form)
        self.input_fileds_frame.setGeometry(QtCore.QRect(220, 30, 541, 581))
        self.input_fileds_frame.setStyleSheet("\n"
                                              "QFrame{\n"
                                              "background-color: qlineargradient(spread:pad, x1:0.489, y1:0, "
                                              "x2:0.534, y2:1, stop:0 rgba(25, 25, 25, 255), stop:1 rgba(39, 39, 39, "
                                              "255));\n "
                                              " image:null;\n"
                                              "border-radius:30px\n"
                                              "\n"
                                              "}\n"
                                              "QLineEdit {\n"
                                              "    border: 2px solid rgb(0, 93, 159);\n"
                                              "    border-radius: 10px;\n"
                                              "    padding: 15px;\n"
                                              "    background-color: rgb(0, 69, 116);\n"
                                              "    color: rgb(255, 255, 255);\n"
                                              " image:null;\n"
                                              "}\n"
                                              "QLineEdit:hover {\n"
                                              "    border: 2px solid rgb(0, 66, 124);\n"
                                              " image:null;\n"
                                              "}\n"
                                              "QLineEdit:focus {\n"
                                              "    border: 2px solid rgb(206, 206, 206);\n"
                                              "    color: rgb(200, 200, 200);\n"
                                              " image:null;\n"
                                              "}\n"
                                              "QPushButton {\n"
                                              "    border: 2px solid rgb(45, 45, 45);\n"
                                              " image:null;\n"
                                              "    border-radius: 10px;\n"
                                              "    padding: 15px;\n"
                                              "    background-color:rgb(14, 13, 24);\n"
                                              "    color: rgb(255, 255, 255);\n"
                                              "}\n"
                                              "QPushButton:hover {\n"
                                              "    border: 2px solid rgb(0, 66, 124);\n"
                                              " image:null;\n"
                                              "}\n"
                                              "QLabel{\n"
                                              "    border:3px solid  rgb(45, 45, 45);\n"
                                              " image:null;\n"
                                              "    border-radius: 10px;\n"
                                              "    \n"
                                              "    background-color: rgb(6, 63, 104);\n"
                                              "}\n"
                                              "QCheckBox{\n"
                                              "    color: rgb(255, 255, 255);\n"
                                              "    padding: 10px;\n"
                                              " image:null;\n"
                                              "}\n"
                                              "QCheckBox::indicator {\n"
                                              "    border: 3px solid rgb(0, 93, 159);\n"
                                              "    width: 20px;\n"
                                              "    height: 20px;\n"
                                              "    border-radius: 10px;\n"
                                              "    background:rgb(0, 0, 0);\n"
                                              "}\n"
                                              "QCheckBox::indicator:hover {\n"
                                              "    border: 3px solid rgb(255, 255, 255);\n"
                                              "}\n"
                                              "QCheckBox::indicator:checked {\n"
                                              "    background: 3px solid rgb(34, 34, 34);\n"
                                              "    background-image: url(:/icons/icons/cil-check.png);\n"
                                              "}")
        self.input_fileds_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_fileds_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_fileds_frame.setObjectName("input_fileds_frame")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.input_fileds_frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 270, 200, 52))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_2.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
                                      "border-radius: 10px;\n"
                                      "background-color: rgb(85, 170, 255);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.input_fileds_frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 510, 121, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.login(Form))
        self.profile_icon_frame = QtWidgets.QFrame(self.input_fileds_frame)
        self.profile_icon_frame.setGeometry(QtCore.QRect(230, 170, 64, 64))
        self.profile_icon_frame.setMinimumSize(QtCore.QSize(64, 64))
        self.profile_icon_frame.setMaximumSize(QtCore.QSize(64, 64))
        self.profile_icon_frame.setAutoFillBackground(False)
        self.profile_icon_frame.setStyleSheet("image: url(:/background/Resources/user.png);\n"
                                              "border-radius: 10px;\n"
                                              "border: 3px solid rgb(35, 35, 35);\n"
                                              "\n"
                                              "")
        self.profile_icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_icon_frame.setObjectName("profile_icon_frame")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.input_fileds_frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 330, 200, 52))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_3.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
                                      "border-radius: 10px;\n"
                                      "background-color: rgb(85, 170, 255);")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.input_fileds_frame)
        self.label.setGeometry(QtCore.QRect(220, 470, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
                                 "\n"
                                 "")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.input_fileds_frame)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;\n"
                                   "background-color:rgb(31, 31, 31);\n"
                                   "")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Email"))
        self.pushButton.setText(_translate("Form", "Login"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Password"))
        self.label_2.setText(_translate("Form", "Login"))

    def login(self, Form):
        email = self.lineEdit_2.text()
        password = self.lineEdit_3.text()

        db = sqlite3.connect('database.db')
        result = database.read_login(email, password, db)
        user = result.fetchall()

        if len(user) > 0:
            Form.hide()
            self.ui = main_form(user[0][0])
            self.window = QtWidgets.QMainWindow()
            self.ui.setupUi(self.window)
            self.window.show()

        else:
            # QMessageBox.about(self, "Error", "This email already exists")
            print("Email or password is not correct. Please enter again.")



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = login_form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
