# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 640)
        self.topFrame = QtWidgets.QFrame(Form)
        self.topFrame.setGeometry(QtCore.QRect(0, 0, 961, 65))
        self.topFrame.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border-radius:10px;")
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.menuButton = QtWidgets.QPushButton(self.topFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.menuButton.setFont(font)
        self.menuButton.setStyleSheet("color:white\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/background/Resources/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuButton.setIcon(icon)
        self.menuButton.setIconSize(QtCore.QSize(32, 32))
        self.menuButton.setCheckable(False)
        self.menuButton.setAutoDefault(False)
        self.menuButton.setFlat(True)
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout.addWidget(self.menuButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.minButton = QtWidgets.QPushButton(self.topFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.minButton.setFont(font)
        self.minButton.setStyleSheet("color:white\n"
"")
        self.minButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/background/Resources/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon1)
        self.minButton.setIconSize(QtCore.QSize(24, 24))
        self.minButton.setCheckable(False)
        self.minButton.setAutoDefault(False)
        self.minButton.setFlat(True)
        self.minButton.setObjectName("minButton")
        self.horizontalLayout.addWidget(self.minButton)
        self.maxButton = QtWidgets.QPushButton(self.topFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.maxButton.setFont(font)
        self.maxButton.setStyleSheet("color:white\n"
"")
        self.maxButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/background/Resources/maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxButton.setIcon(icon2)
        self.maxButton.setIconSize(QtCore.QSize(24, 24))
        self.maxButton.setCheckable(False)
        self.maxButton.setAutoDefault(False)
        self.maxButton.setFlat(True)
        self.maxButton.setObjectName("maxButton")
        self.horizontalLayout.addWidget(self.maxButton)
        self.closeButton = QtWidgets.QPushButton(self.topFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet("color:white\n"
"")
        self.closeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/background/Resources/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QtCore.QSize(24, 24))
        self.closeButton.setCheckable(False)
        self.closeButton.setAutoDefault(False)
        self.closeButton.setFlat(True)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.mainFrame = QtWidgets.QFrame(Form)
        self.mainFrame.setGeometry(QtCore.QRect(0, 50, 961, 591))
        self.mainFrame.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border-radius:30px;")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.middleFrame = QtWidgets.QFrame(self.mainFrame)
        self.middleFrame.setGeometry(QtCore.QRect(11, 11, 941, 571))
        self.middleFrame.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.middleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middleFrame.setObjectName("middleFrame")
        self.leftFrame = QtWidgets.QFrame(self.middleFrame)
        self.leftFrame.setGeometry(QtCore.QRect(10, 10, 301, 181))
        self.leftFrame.setMinimumSize(QtCore.QSize(180, 0))
        self.leftFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftFrame.setStyleSheet("background-color:rgba(25, 25, 25, 255);\n"
"border-radius:30px")
        self.leftFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.homeButton = QtWidgets.QPushButton(self.leftFrame)
        self.homeButton.setGeometry(QtCore.QRect(0, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.homeButton.setFont(font)
        self.homeButton.setStyleSheet("color:white\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/background/Resources/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon4)
        self.homeButton.setIconSize(QtCore.QSize(32, 32))
        self.homeButton.setCheckable(False)
        self.homeButton.setAutoDefault(False)
        self.homeButton.setFlat(True)
        self.homeButton.setObjectName("homeButton")
        self.profileButton = QtWidgets.QPushButton(self.leftFrame)
        self.profileButton.setGeometry(QtCore.QRect(0, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.profileButton.setFont(font)
        self.profileButton.setStyleSheet("color:white\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/background/Resources/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profileButton.setIcon(icon5)
        self.profileButton.setIconSize(QtCore.QSize(32, 32))
        self.profileButton.setCheckable(False)
        self.profileButton.setAutoDefault(False)
        self.profileButton.setFlat(True)
        self.profileButton.setObjectName("profileButton")
        self.cartButton = QtWidgets.QPushButton(self.leftFrame)
        self.cartButton.setGeometry(QtCore.QRect(150, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.cartButton.setFont(font)
        self.cartButton.setStyleSheet("color:white\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/background/Resources/cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartButton.setIcon(icon6)
        self.cartButton.setIconSize(QtCore.QSize(32, 32))
        self.cartButton.setCheckable(False)
        self.cartButton.setAutoDefault(False)
        self.cartButton.setFlat(True)
        self.cartButton.setObjectName("cartButton")
        self.stackedWidget = QtWidgets.QStackedWidget(self.middleFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, 0, 941, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.login_form_frame = QtWidgets.QFrame(self.home)
        self.login_form_frame.setGeometry(QtCore.QRect(20, 10, 911, 551))
        self.login_form_frame.setMinimumSize(QtCore.QSize(450, 350))
        self.login_form_frame.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.login_form_frame.setStyleSheet("border-radius: 20px;\n"
"")
        self.login_form_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_form_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_form_frame.setObjectName("login_form_frame")
        self.input_fileds_frame = QtWidgets.QFrame(self.login_form_frame)
        self.input_fileds_frame.setGeometry(QtCore.QRect(180, 0, 541, 551))
        self.input_fileds_frame.setStyleSheet("QFrame{\n"
"\n"
"    \n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.534, y2:1, stop:0 rgba(25, 25, 25, 255), stop:1 rgba(39, 39, 39, 255));\n"
"\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid rgb(0, 93, 159);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(0, 69, 116);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(206, 206, 206);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color:rgb(14, 13, 24);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0, 66, 124);\n"
"}\n"
"QLabel{\n"
"    border:3px solid  rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(6, 63, 104);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 10px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(0, 93, 159);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background:rgb(0, 0, 0);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(34, 34, 34);\n"
"    background-image: url(:/icons/icons/cil-check.png);\n"
"}")
        self.input_fileds_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_fileds_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_fileds_frame.setObjectName("input_fileds_frame")
        self.lineEdit = QtWidgets.QLineEdit(self.input_fileds_frame)
        self.lineEdit.setGeometry(QtCore.QRect(160, 210, 200, 52))
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.input_fileds_frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 270, 200, 52))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_2.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.input_fileds_frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 480, 121, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.profile_icon_frame = QtWidgets.QFrame(self.input_fileds_frame)
        self.profile_icon_frame.setGeometry(QtCore.QRect(230, 70, 64, 64))
        self.profile_icon_frame.setMinimumSize(QtCore.QSize(64, 64))
        self.profile_icon_frame.setMaximumSize(QtCore.QSize(64, 64))
        self.profile_icon_frame.setAutoFillBackground(False)
        self.profile_icon_frame.setStyleSheet("image: url(:/background/Resources/user.png);\n"
"border-radius: 10px;\n"
"border: 3px solid rgb(35, 35, 35);\n"
"\n"
"")
        self.profile_icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile_icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile_icon_frame.setObjectName("profile_icon_frame")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.input_fileds_frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 330, 200, 52))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_3.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.input_fileds_frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 390, 200, 52))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(200, 50))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_4.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.stackedWidget.addWidget(self.home)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.cart = QtWidgets.QFrame(self.profile)
        self.cart.setGeometry(QtCore.QRect(20, 10, 911, 551))
        self.cart.setMinimumSize(QtCore.QSize(450, 350))
        self.cart.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.cart.setStyleSheet("border-radius: 20px;\n"
"")
        self.cart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cart.setObjectName("cart")
        self.tableView = QtWidgets.QTableView(self.cart)
        self.tableView.setGeometry(QtCore.QRect(170, 10, 601, 541))
        self.tableView.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.tableView.setObjectName("tableView")
        self.homeButton_3 = QtWidgets.QPushButton(self.cart)
        self.homeButton_3.setGeometry(QtCore.QRect(0, 510, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.homeButton_3.setFont(font)
        self.homeButton_3.setStyleSheet("color:white;\n"
"background-color: rgb(150, 150, 150);\n"
"border-radius:10px\n"
"")
        self.homeButton_3.setIconSize(QtCore.QSize(32, 32))
        self.homeButton_3.setCheckable(False)
        self.homeButton_3.setAutoDefault(False)
        self.homeButton_3.setFlat(True)
        self.homeButton_3.setObjectName("homeButton_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.cart)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 430, 151, 50))
        self.lineEdit_5.setMinimumSize(QtCore.QSize(100, 50))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_5.setStyleSheet("border:3px solid  rgb(43, 31, 91);\n"
"border-radius: 10px;\n"
"background-color: rgb(85, 170, 255);")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.stackedWidget.addWidget(self.profile)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(640, 50, 291, 451))
        self.frame.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 251, 291))
        self.frame_2.setStyleSheet("image: url(:/background/Resources/telescope2.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 290, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.homeButton_2 = QtWidgets.QPushButton(self.frame)
        self.homeButton_2.setGeometry(QtCore.QRect(90, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.homeButton_2.setFont(font)
        self.homeButton_2.setStyleSheet("color:white;\n"
"background-color: rgb(59, 59, 59);\n"
"border-radius:10px;\n"
"")
        self.homeButton_2.setIconSize(QtCore.QSize(32, 32))
        self.homeButton_2.setCheckable(False)
        self.homeButton_2.setAutoDefault(False)
        self.homeButton_2.setFlat(True)
        self.homeButton_2.setObjectName("homeButton_2")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(330, 50, 291, 451))
        self.frame_3.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(20, 10, 251, 291))
        self.frame_5.setStyleSheet("image:url(:/background/Resources/toy2.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(70, 290, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.homeButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.homeButton_4.setGeometry(QtCore.QRect(90, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.homeButton_4.setFont(font)
        self.homeButton_4.setStyleSheet("color:white;\n"
"background-color: rgb(59, 59, 59);\n"
"border-radius:10px;\n"
"")
        self.homeButton_4.setIconSize(QtCore.QSize(32, 32))
        self.homeButton_4.setCheckable(False)
        self.homeButton_4.setAutoDefault(False)
        self.homeButton_4.setFlat(True)
        self.homeButton_4.setObjectName("homeButton_4")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setGeometry(QtCore.QRect(20, 50, 291, 451))
        self.frame_6.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(20, 10, 251, 291))
        self.frame_8.setStyleSheet("image: url(:/background/Resources/telescope1.png);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(70, 290, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setObjectName("label_5")
        self.homeButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.homeButton_6.setGeometry(QtCore.QRect(90, 390, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.homeButton_6.setFont(font)
        self.homeButton_6.setStyleSheet("color:white;\n"
"background-color: rgb(59, 59, 59);\n"
"border-radius:10px;\n"
"")
        self.homeButton_6.setIconSize(QtCore.QSize(32, 32))
        self.homeButton_6.setCheckable(False)
        self.homeButton_6.setAutoDefault(False)
        self.homeButton_6.setFlat(True)
        self.homeButton_6.setObjectName("homeButton_6")
        self.stackedWidget.addWidget(self.page)
        self.stackedWidget.raise_()
        self.leftFrame.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.menuButton.setText(_translate("Form", "Menu"))
        self.homeButton.setText(_translate("Form", "Home"))
        self.profileButton.setText(_translate("Form", "Profile"))
        self.cartButton.setText(_translate("Form", "Cart"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Email"))
        self.pushButton.setText(_translate("Form", "Update"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Password"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Phone"))
        self.homeButton_3.setText(_translate("Form", "Delete"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "ID"))
        self.label.setText(_translate("Form", "Kosmos Astro Telescope"))
        self.homeButton_2.setText(_translate("Form", "Buy"))
        self.label_3.setText(_translate("Form", "Saturn Plush Toy"))
        self.homeButton_4.setText(_translate("Form", "Buy"))
        self.label_5.setText(_translate("Form", "LX200 Telescope"))
        self.homeButton_6.setText(_translate("Form", "Buy"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
